name: .NET

on:
  push:
    branches: [ "master", "work" ]
  pull_request:
    branches: [ "master", "work" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore KeyboardApp.sln
    - name: Build
      run: dotnet build KeyboardApp.sln --no-restore
    - name: Test
      run: dotnet test KeyboardApp.sln --no-build --verbosity normal
